publish_mode: editorial_workflow
media_folder: "assets/uploads"

backend:
  name: git-gateway
  repo: https://github.com/sites-yari/editval-consultorio-netlify
  branch: dev # Branch to update (optional; defaults to master)
  site_domain: consultoria-editvalue.netlify.com

collections:
#====================| POSTS |===================================================|  
  #-----| Read me |------------------------------|
  - name: "posts"
    label: "Instruções"
    folder: "_posts"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data de publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD" }

  #-----| Artigos |-------------------------------|
  - name: "artigos-economia"
    label: "Artigos de Economia"
    folder: "_posts/artigos-economia"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "for-post-text" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "data", widget: "datetime", format: "DD-MM-YYYY" }
      - { label: "Autor", name: "autor", widget: "string" }
      - { label: "Categoria", name: "category", widget: "hidden", default: "artigos" }
      - { label: "Classe", name: "class", widget: "hidden", default: "media-pt" }
      - { label: "Activo", name: "media_active?", widget: "hidden", default: "active" }
      - { label: "Formação?", name: "formacao?", widget: "hidden", default: "artigos-economia" }
      - { label: "Contexto", name: "body", widget: "markdown" }

  #-----| Clipping |------------------------------|
  - name: "clipping"
    label: "Clipping"
    folder: "_posts/clipping"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "for-post" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Categoria", name: "category", widget: "hidden", default: "clipping" }
      - { label: "Imagem de Capa", name: "main_image_path", widget: "image" }
      - { label: "Classe", name: "class", widget: "hidden", default: "media-pt" }
      - { label: "Media Active?", name: "media_active?", widget: "hidden", default: "active" }
      - { label: "Formação?", name: "formacao?", widget: "hidden", default: "clipping" }
      - { label: "Nome do Endereço", name: "permalink", widget: "string", default: "pt-media/clipping/recortes-" }
      - label: "Lista de Imagens"
        name: "image_list"
        widget: "list"
        fields:
          - { label: "Imagem", name: "image_path", widget: "image" }
          - { label: "Endereço de Imagem", name: "link_image_path", widget: "image" }
          - { label: "Titulo da Image", name: "subtitles", widget: "string" }
          - { label: "Data publicada", name: "date", widget: "datetime", format: "DD-MM-YYYY" } 

  #-----| Galeria de fotos |----------------------|
  - name: "galeria-fotos"
    label: "Galeria de fotos"
    folder: "_posts/galeria-fotos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "media-post" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Categoria", name: "category", widget: "hidden", default: "galeria-de-fotos" }
      - { label: "Imagem de capa", name: "main_image_path", widget: "image" }
      - { label: "Classe", name: "class", widget: "hidden", default: "media-pt" }
      - { label: "Media Active?", name: "media_active?", widget: "hidden", default: "active" }
      - { label: "Formação?", name: "formacao?", widget: "hidden", default: "galeria-fotos" }
      - { label: "Nome do Endereço", name: "permalink", widget: "string", default: "pt-media/galeria-fotos/(nome)" }
      - label: "Lista de Imagens"
        name: "image_list"
        widget: "list"
        fields:
          - { label: "Imagem", name: "image_path", widget: "image" }
          - { label: "Endereço de Imagem", name: "link_image_path", widget: "image" }

  #-----| Press release |-------------------------|
  - name: "press-release"
    label: "Press Release"
    folder: "_posts/press-release"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "for-post-text" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "data", widget: "datetime", format: "DD-MM-YYYY" }
      - { label: "Categoria", name: "category", widget: "hidden", default: "press-release" }
      - { label: "Classe", name: "class", widget: "hidden", default: "media-pt" }
      - { label: "Media Active?", name: "media_active?", widget: "hidden", default: "active" }
      - { label: "Formação?", name: "formacao?", widget: "press-release" }
      - { label: "Descrição do titulo", name: "body", widget: "markdown" }

  #-----| Redes |---------------------------------|
  - name: "redes"
    label: "Redes"
    folder: "_posts/redes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Categoria", name: "category", widget: "hidden", default: "Parcerias" }
      - { label: "Imagem", name: "imagem_image_path", widget: "image" }
      - { label: "Endereço/link", name: "link", widget: "string" }
      - { label: "Descrição", name: "text", widget: "string" }
#====================| DATA |====================================================|  


