publish_mode: editorial_workflow
media_folder: "assets/uploads"

backend:
  name: git-gateway
  repo: https://lepen@bitbucket.org/lepen/editvalue-consultoria-netlify.git
  branch: dev # Branch to update (optional; defaults to master)
  site_domain: author-goat-77256.netlify.com

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data de publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma" }
